{"name": "Попытка авторизации с неверными данными", "status": "passed", "start": 1722281605144, "stop": 1722281605354, "uuid": "95cae9a0-ef94-4168-b681-90d688629cec", "historyId": "03420e715c12f56e7e5c2808d1ca3a29", "testCaseId": "03420e715c12f56e7e5c2808d1ca3a29", "fullName": "tests.test_user_login.TestUserLogin#test_login_invalid_credentials", "labels": [{"name": "feature", "value": "Авторизация пользователя"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_login"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "DESKTOP-HPT8HPV"}, {"name": "thread", "value": "15172-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_login"}]}